name: CI
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, labeled, synchronize]
    branches:
      - main
jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: dreamer2368/librom_env:latest
      options: --user 1001 --privileged
      volumes:
        - /mnt:/mnt
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Check out pylibROM
        uses: actions/checkout@v1
        with:
            submodules: 'true'
      - name: build
        run: |
            cd extern/libROM
            ./scripts/compile.sh -m
            echo built pylibROM
            cd ../../
            pip install ./
      - name: test
        run: |
            cd tests
            echo run pyVector unit test
            pytest test_pyVector.py
            echo run pyMatrix unit test
            pytest test_pyMatrix.py
